version: "3"
services:
  db:
    container_name: pg
    restart: always
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - default

  app:
    container_name: app
    restart: always
    build:
      context: .
    env_file: .env
    ports:
      - 80:5000
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default

volumes:
  pg_data:
