version: "3"
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db-app-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    container_name: app
    restart: always
    build:
      context: .
    env_file: .env
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  flask-app-db:
    name: flask-app-db