"""empty message

Revision ID: d2ece6d4e2df
Revises: f7cad1f7665a
Create Date: 2021-10-01 19:53:52.876060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ece6d4e2df'
down_revision = 'f7cad1f7665a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('patients', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'created_at')
    op.drop_column('patients', 'updated_at')
    # ### end Alembic commands ###
