"""empty message

Revision ID: dba7c5616bc9
Revises: d2ece6d4e2df
Create Date: 2021-10-01 20:21:31.793262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba7c5616bc9'
down_revision = 'd2ece6d4e2df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'updated_at')
    # ### end Alembic commands ###
